# Generated by Django 5.2.3 on 2025-07-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_aula_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='video_id',
            field=models.CharField(max_length=64),
        ),
    ]
