# Generated by Django 5.2.3 on 2025-07-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('titulo', models.CharField(max_length=32)),
                ('synthesia_id', models.CharField(max_length=64)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
