name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PIPENV_VENV_IN_PROJECT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
      
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar pipenv e dependências
        run: |          
          pip install --quiet pipenv
          pipenv sync -d
          # Instala pytest, pytest-cov e codecov caso não estejam no Pipfile
          pipenv run pip install --quiet pytest pytest-cov codecov
          pipenv install gunicorn
          cp contrib/env-sample .env

      - name: Rodar Flake8 e Pytest
        run: |
          pipenv run flake8 .          

      - name: Rodar Pytest com cobertura
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pipenv run pytest --cov=pypro --cov-report=xml

      - name: Enviar cobertura para Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
