name: Deploy na EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Subir containers
        run: |
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
